# Configuration for actions/labeler
# Docs: https://github.com/actions/labeler

"area: astro-bun":
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/astro-bun/**'

"area: examples":
  - changed-files:
      - any-glob-to-any-file:
          - 'examples/**'

"area: ci":
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/labeler.yaml'

"area: docs":
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '**/*.mdx'
      - all-globs-to-all-files:
          - '!.github/**'

"area: chore":
  - changed-files:
      - all-globs-to-all-files:
          - '!packages/**'
          - '!examples/**'
          - '!.github/**'
          - '!**/*.md'
          - '!**/*.mdx'

"area: github":
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
      - all-globs-to-all-files:
          - '!.github/workflows/**'
          - '!.github/labeler.yaml'
