# Configuration for actions/labeler
# Docs: https://github.com/actions/labeler

"topic: packages":
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/**'

"name: astro-bun":
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/astro-bun/**'

"topic: examples":
  - changed-files:
      - any-glob-to-any-file:
          - 'examples/**'

"topic: ci":
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/labeler.yaml'

"topic: docs":
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '**/*.mdx'
          - '!examples/**'

"topic: governance":
  - changed-files:
      - any-glob-to-any-file:
          - '.github/ISSUE_TEMPLATE/**'
          - '.github/PULL_REQUEST_TEMPLATE**'
          - '.github/CONTRIBUTING.md'
          - '**/LICENSE'
          - '**/LICENSE.*'
          - 'LICENSE'

"topic: repository":
  - changed-files:
      - all-globs-to-all-files:
          - 'tools/**'
          - '!packages/**'
          - '!examples/**'
          - '!.github/**'
          - '!**/*.md'
          - '!**/*.mdx'
          - '!**/LICENSE'
          - '!**/LICENSE.*'
          - '!LICENSE'
