name: "Pull Request / Stage 2"

on:
  workflow_run:
    workflows: ["Pull Request / Stage 1"]
    types: [completed]

permissions: {}

jobs:
  label:
    name: Label
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: >- # https://github.com/actions/checkout/releases/tag/v6.0.2
          actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Resolve PR
        id: pr
        uses: ./.github/actions/resolve

      - name: Generate App Token
        id: app-token
        uses: >- # https://github.com/actions/create-github-app-token/releases/tag/v3.1.1
          actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Apply labels
        uses: >- # https://github.com/actions/labeler/releases/tag/v6.0.1
          actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          configuration-path: .github/labeler.yaml
          sync-labels: true
          pr-number: ${{ steps.pr.outputs.number }}
